### ISSUE TITLE
Note Type, we have currently

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb.js#60]
Right now we have 2 types `Note` with the same goal one of them is on `wasm-utils` and the other is on the typescript.

the note is required on the UI for some action, we don't have direct communication as we pass the `Note to the worker as a string, however, in the future, there might be changes on serialization and deserialization
Solution
1. Maintain both
2. Have the Note on one side I guess it will be wasm, then we have to load wasm on the main thread :(
3. ~Have them on typescript~

**Comment by drewstone** [comment]
Can you link both Notes that you're referring to?

**Comment by shekohex** [comment]
> Can you link both Notes that you're referring to?

The first one (in Typescript): https://github.com/webb-tools/webb.js/blob/master/packages/sdk-mixer/src/note.ts#L4

The second one (in WASM): https://github.com/webb-tools/webb.js/blob/master/packages/wasm-utils/src/lib.rs#L88

in my opinion, we should keep it in WASM and make WASM our source of truth here, since the wasm code is likely to be shared between CLI and WASM, also `sdk-merkle` and other packages in the future.

**Comment by drewstone** [comment]
What I would like to see if better coupling of the TS with the WASM. I do support having both at the moment since it seems like we may benefit from having TS interfaces for our products as well.

On the coupling side, I think we should mock the WASM functions in the Typescript directly. Do you think that's a bad idea? This way we don't rewrite logic but merely provide another location for its usage.

**Comment by shekohex** [comment]
WASM already exposes a TS interface with the correct types with a very nice API that we can depend on it.
What we can do, for now, is write another thin layer on it for example the Note that is defined in TS should have an `inner: wasm.Note` that loads wasm Note class and forward any calls to the underlying wasm implementation.
